version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: EsportDB
    ports:
      - "3306:3306"

  backend:
    build: ../server
    ports:
      - "5000:5000"
    depends_on:
      - db 

  frontend:
    build: ../client
    ports:
      - "3000:3000"